Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(eval_runs.py:21794): Gdk-CRITICAL **: 17:31:08.317: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "scripts/train_cifar/eval/eval_runs.py", line 11, in <module>
    from utils import *
  File "/usr/project/xtmp/CSPlus/VOLDNN/Annie/mli-release/scripts/train_cifar/eval/utils.py", line 13, in <module>
    from mli.models import interpolate_state, get_activation_function
ModuleNotFoundError: No module named 'mli'
